
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/better_call_buffet
      - PROJECT_NAME=Better Call Buffet
      - API_V1_PREFIX=/api/v1
      - SECRET_KEY=development-secret-key-change-in-production
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    depends_on:
      - db
    volumes:
      - .:/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=better_call_buffet
    ports:
      - "5432:5432"

volumes:
  postgres_data: 