# fly.toml app configuration file generated for better-call-buffet on 2025-07-12T13:40:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'better-call-buffet-prod'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'alembic stamp head'
  strategy = 'rolling'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
