[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./scripts/run-railway.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
[services.web]
source = "."