[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./scripts/run-prod.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
configPrecedence = "project"