"""update_credit_card

Revision ID: 014a78e888b0
Revises: 6513790b02ea
Create Date: 2025-06-15 13:56:58.706699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "014a78e888b0"
down_revision: Union[str, None] = "6513790b02ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_cards", sa.Column("last_four_digits", sa.String(), nullable=True)
    )
    op.drop_index("ix_credit_cards_last_four", table_name="credit_cards")
    op.create_index(
        op.f("ix_credit_cards_last_four_digits"),
        "credit_cards",
        ["last_four_digits"],
        unique=False,
    )
    op.drop_column("credit_cards", "last_four")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_cards",
        sa.Column("last_four", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_credit_cards_last_four_digits"), table_name="credit_cards")
    op.create_index(
        "ix_credit_cards_last_four", "credit_cards", ["last_four"], unique=False
    )
    op.drop_column("credit_cards", "last_four_digits")
    # ### end Alembic commands ###
