"""Updating Broker

Revision ID: 118723dfa508
Revises: 1e6bddf752ab
Create Date: 2025-06-08 14:07:24.688133

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "118723dfa508"
down_revision: Union[str, None] = "1e6bddf752ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brokers", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column("brokers", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "brokers", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "brokers", type_="foreignkey")
    op.drop_column("brokers", "is_active")
    op.drop_column("brokers", "user_id")
    # ### end Alembic commands ###
