"""Remove balance fields from accounts

Revision ID: 367713119700
Revises: a743b38b7ea6
Create Date: 2025-09-19 21:16:51.922188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '367713119700'
down_revision: Union[str, None] = 'a743b38b7ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_accounts_last_transaction'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'available_balance')
    op.drop_column('accounts', 'balance_updated_at')
    op.drop_column('accounts', 'last_transaction_id')
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('last_transaction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('balance_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('available_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_accounts_last_transaction'), 'accounts', 'transactions', ['last_transaction_id'], ['id'])
    # ### end Alembic commands ###
