"""Remove credit card fields from statements table

Revision ID: 39758f577ff3
Revises: bf7e914a3141
Create Date: 2025-10-02 02:45:59.006034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39758f577ff3'
down_revision: Union[str, None] = 'bf7e914a3141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'min_payment')
    op.drop_column('statements', 'due_date')
    op.drop_column('statements', 'total_due')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('total_due', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('min_payment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
