"""Add indexes for timeline queries

Revision ID: 3ba35655589e
Revises: 5d69043817b1
Create Date: 2025-12-13 20:40:02.285674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba35655589e'
down_revision: Union[str, None] = '5d69043817b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transactions_account_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_index('idx_transactions_account_date_amount', 'transactions', ['account_id', 'date', 'amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_account_date_amount', table_name='transactions')
    op.drop_index('idx_transactions_account_date', table_name='transactions')
    # ### end Alembic commands ###
