"""add_broker_id_to_accounts_table

Revision ID: 3e1b83acf33f
Revises: d6ebeded3cc2
Create Date: 2025-06-14 19:16:38.572922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1b83acf33f'
down_revision: Union[str, None] = 'd6ebeded3cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('raw_content', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('balance_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_balance_points_account_id', 'balance_points', ['account_id'], unique=False)
    op.create_index('ix_balance_points_date', 'balance_points', ['date'], unique=False)
    op.create_index(op.f('ix_balance_points_id'), 'balance_points', ['id'], unique=False)
    op.add_column('accounts', sa.Column('broker_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'brokers', ['broker_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'broker_id')
    op.drop_index(op.f('ix_balance_points_id'), table_name='balance_points')
    op.drop_index('ix_balance_points_date', table_name='balance_points')
    op.drop_index('ix_balance_points_account_id', table_name='balance_points')
    op.drop_table('balance_points')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
