"""Make broker_id non-nullable in accounts table

Revision ID: 4714248eb752
Revises: 3e1b83acf33f
Create Date: 2025-06-14 20:09:49.646333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4714248eb752'
down_revision: Union[str, None] = '3e1b83acf33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'broker_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'broker_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
