"""make_broker_logo_nullable

Revision ID: 47fa2f57d26e
Revises: 0a37f37a027e
Create Date: 2025-06-30 17:33:33.883858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47fa2f57d26e'
down_revision: Union[str, None] = '0a37f37a027e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brokers', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'invoices', 'credit_cards', ['credit_card_id'], ['id'])
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_created_at', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('brokers', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
