"""update_credit_card

Revision ID: 6513790b02ea
Revises: 710bf3b90f98
Create Date: 2025-06-15 13:55:08.762956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6513790b02ea'
down_revision: Union[str, None] = '710bf3b90f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('credit_limit', sa.Float(), nullable=True))
    op.add_column('credit_cards', sa.Column('last_four', sa.String(), nullable=True))
    op.drop_index('ix_credit_cards_balance', table_name='credit_cards')
    op.create_index(op.f('ix_credit_cards_credit_limit'), 'credit_cards', ['credit_limit'], unique=False)
    op.create_index(op.f('ix_credit_cards_last_four'), 'credit_cards', ['last_four'], unique=False)
    op.drop_column('credit_cards', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_credit_cards_last_four'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_credit_limit'), table_name='credit_cards')
    op.create_index('ix_credit_cards_balance', 'credit_cards', ['balance'], unique=False)
    op.drop_column('credit_cards', 'last_four')
    op.drop_column('credit_cards', 'credit_limit')
    # ### end Alembic commands ###
