"""Add calculated_at field to balance_points

Revision ID: 6b3a6211eb8f
Revises: 367713119700
Create Date: 2025-09-21 14:29:10.103667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3a6211eb8f'
down_revision: Union[str, None] = '367713119700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_points', sa.Column('calculated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_balance_points_account_calculated_at', 'balance_points', ['account_id', 'calculated_at'], unique=False)
    op.create_index('ix_balance_points_calculated_at', 'balance_points', ['calculated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_balance_points_calculated_at', table_name='balance_points')
    op.drop_index('ix_balance_points_account_calculated_at', table_name='balance_points')
    op.drop_column('balance_points', 'calculated_at')
    # ### end Alembic commands ###
