"""add_installments_domain

Revision ID: 73b3011447a9
Revises: ccfe01907341
Create Date: 2025-12-31 14:48:46.035864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b3011447a9'
down_revision: Union[str, None] = 'ccfe01907341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'finished', 'cancelled', name='installmentplanstatus'), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('credit_card_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['user_categories.id'], ),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_installment_plans_credit_card_id', 'installment_plans', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_installment_plans_id'), 'installment_plans', ['id'], unique=False)
    op.create_index('ix_installment_plans_user_id', 'installment_plans', ['user_id'], unique=False)
    op.create_table('installments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'linked', name='installmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_installments_due_date', 'installments', ['due_date'], unique=False)
    op.create_index(op.f('ix_installments_id'), 'installments', ['id'], unique=False)
    op.create_index('ix_installments_plan_id', 'installments', ['plan_id'], unique=False)
    op.add_column('transactions', sa.Column('installment_id', sa.UUID(), nullable=True))
    op.create_index('idx_transactions_installment_id', 'transactions', ['installment_id'], unique=False)
    op.create_foreign_key('transactions_installment_id_fkey', 'transactions', 'installments', ['installment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_installment_id_fkey', 'transactions', type_='foreignkey')
    op.drop_index('idx_transactions_installment_id', table_name='transactions')
    op.drop_column('transactions', 'installment_id')
    op.drop_index('ix_installments_plan_id', table_name='installments')
    op.drop_index(op.f('ix_installments_id'), table_name='installments')
    op.drop_index('ix_installments_due_date', table_name='installments')
    op.drop_table('installments')
    op.drop_index('ix_installment_plans_user_id', table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_id'), table_name='installment_plans')
    op.drop_index('ix_installment_plans_credit_card_id', table_name='installment_plans')
    op.drop_table('installment_plans')
    # ### end Alembic commands ###
