"""add_user_id_and_timestamps_to_transactions

Revision ID: a4585da3b8de
Revises: user_schema_migration_step2
Create Date: 2025-06-30 20:36:31.519349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4585da3b8de'
down_revision: Union[str, None] = 'user_schema_migration_step2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invoices', 'credit_cards', ['credit_card_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('transactions', 'broker_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'broker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    # ### end Alembic commands ###
