"""add user categories table and 
  category_id to transactions

Revision ID: a6826185c146
Revises: 928971a0a0f3
Create Date: 2025-12-21 14:20:44.685967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6826185c146'
down_revision: Union[str, None] = '928971a0a0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['user_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'parent_id', name='uq_user_category_name')
    )
    op.create_index('idx_user_categories_user_active', 'user_categories', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_user_categories_user_parent', 'user_categories', ['user_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    op.create_index(op.f('ix_user_categories_user_id'), 'user_categories', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('category_id', sa.UUID(), nullable=True))
    # Backfill NULL values in 'ignored' column before making it NOT NULL
    op.execute("UPDATE transactions SET ignored = FALSE WHERE ignored IS NULL")
    op.alter_column('transactions', 'ignored',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'transactions', 'user_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'ignored',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('transactions', 'category_id')
    op.drop_index(op.f('ix_user_categories_user_id'), table_name='user_categories')
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.drop_index('idx_user_categories_user_parent', table_name='user_categories')
    op.drop_index('idx_user_categories_user_active', table_name='user_categories')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
