"""test_clean_migration

Revision ID: adcab795f51c
Revises: user_schema_migration_step2
Create Date: 2025-06-30 20:28:29.983717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcab795f51c'
down_revision: Union[str, None] = 'user_schema_migration_step2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invoices', 'credit_cards', ['credit_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    # ### end Alembic commands ###
