"""Add stale tracking fields to balance_points

Revision ID: bf7e914a3141
Revises: 6b3a6211eb8f
Create Date: 2025-10-01 23:20:10.947291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7e914a3141'
down_revision: Union[str, None] = '6b3a6211eb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_stale column with default value for existing rows
    op.add_column('balance_points', sa.Column('is_stale', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('balance_points', sa.Column('stale_reason', sa.String(), nullable=True))
    op.add_column('balance_points', sa.Column('last_validated', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('balance_points_source_transaction_id_fkey'), 'balance_points', type_='foreignkey')
    op.create_foreign_key(None, 'balance_points', 'transactions', ['source_transaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance_points', type_='foreignkey')
    op.create_foreign_key(op.f('balance_points_source_transaction_id_fkey'), 'balance_points', 'transactions', ['source_transaction_id'], ['id'])
    op.drop_column('balance_points', 'last_validated')
    op.drop_column('balance_points', 'stale_reason')
    op.drop_column('balance_points', 'is_stale')
    # ### end Alembic commands ###
