"""add_subscriptions_table_and_link_to_transactions

Revision ID: ccfe01907341
Revises: 6ba2683dab3b
Create Date: 2025-12-27 17:54:02.104636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfe01907341'
down_revision: Union[str, None] = '6ba2683dab3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.Enum('weekly', 'monthly', 'quarterly', 'yearly', name='billingcycle'), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['user_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_vendor_id', 'subscriptions', ['vendor_id'], unique=False)
    op.add_column('transactions', sa.Column('vendor_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('subscription_id', sa.UUID(), nullable=True))
    op.create_index('idx_transactions_subscription_id', 'transactions', ['subscription_id'], unique=False)
    op.create_index('idx_transactions_vendor_id', 'transactions', ['vendor_id'], unique=False)
    op.create_foreign_key('transactions_vendor_id_fkey', 'transactions', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key('transactions_subscription_id_fkey', 'transactions', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_subscription_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_vendor_id_fkey', 'transactions', type_='foreignkey')
    op.drop_index('idx_transactions_vendor_id', table_name='transactions')
    op.drop_index('idx_transactions_subscription_id', table_name='transactions')
    op.drop_column('transactions', 'subscription_id')
    op.drop_column('transactions', 'vendor_id')
    op.drop_index('ix_subscriptions_vendor_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
