"""Add created_at and updated_at to brokers table

Revision ID: d6ebeded3cc2
Revises: 118723dfa508
Create Date: 2025-06-08 14:18:31.672115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6ebeded3cc2"
down_revision: Union[str, None] = "118723dfa508"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brokers", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("brokers", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brokers", "updated_at")
    op.drop_column("brokers", "created_at")
    # ### end Alembic commands ###
