"""Add is_deleted column to invoices

Revision ID: db4bccc65efd
Revises: 001_initial_schema
Create Date: 2025-08-10 20:46:47.563193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4bccc65efd'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_points', sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('balance_points', sa.Column('available_balance', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.drop_column('balance_points', 'points')
    op.add_column('invoices', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'is_deleted')
    op.add_column('balance_points', sa.Column('points', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_column('balance_points', 'available_balance')
    op.drop_column('balance_points', 'balance')
    # ### end Alembic commands ###
