"""Refactor balance_points 
  domain with timeline tracking

Revision ID: e495b5c46617
Revises: aa504042a833
Create Date: 2025-10-28 13:36:30.766841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e495b5c46617'
down_revision: Union[str, None] = 'aa504042a833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first (will be backfilled in hotfix migration, then set to NOT NULL)
    op.add_column('balance_points', sa.Column('timeline_status', sa.String(), nullable=True))
    op.add_column('balance_points', sa.Column('has_transactions', sa.Boolean(), nullable=True))
    op.alter_column('balance_points', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('balance_points', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_index(op.f('ix_balance_points_account_calculated_at'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_account_id'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_calculated_at'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_credit_card_id'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_date'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_snapshot_type'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_source_transaction'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_user_date'), table_name='balance_points')
    op.drop_index(op.f('ix_balance_points_verified'), table_name='balance_points')
    op.create_index('ix_balance_points_account_date', 'balance_points', ['account_id', 'date'], unique=False)
    op.create_index('ix_balance_points_account_status', 'balance_points', ['account_id', 'timeline_status'], unique=False)
    op.create_index('ix_balance_points_status', 'balance_points', ['timeline_status'], unique=False)
    op.create_unique_constraint('uix_balance_points_account_date', 'balance_points', ['account_id', 'date'])
    op.drop_constraint(op.f('balance_points_credit_card_id_fkey'), 'balance_points', type_='foreignkey')
    op.drop_constraint(op.f('balance_points_source_transaction_id_fkey'), 'balance_points', type_='foreignkey')
    op.drop_constraint(op.f('balance_points_user_id_fkey'), 'balance_points', type_='foreignkey')
    op.drop_column('balance_points', 'stale_reason')
    op.drop_column('balance_points', 'source_transaction_id')
    op.drop_column('balance_points', 'is_stale')
    op.drop_column('balance_points', 'snapshot_type')
    op.drop_column('balance_points', 'calculated_at')
    op.drop_column('balance_points', 'is_verified')
    op.drop_column('balance_points', 'note')
    op.drop_column('balance_points', 'user_id')
    op.drop_column('balance_points', 'available_balance')
    op.drop_column('balance_points', 'credit_card_id')
    op.drop_column('balance_points', 'last_validated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_points', sa.Column('last_validated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('balance_points', sa.Column('credit_card_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('balance_points', sa.Column('available_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('balance_points', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('balance_points', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('balance_points', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('balance_points', sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('balance_points', sa.Column('snapshot_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('balance_points', sa.Column('is_stale', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('balance_points', sa.Column('source_transaction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('balance_points', sa.Column('stale_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('balance_points_user_id_fkey'), 'balance_points', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('balance_points_source_transaction_id_fkey'), 'balance_points', 'transactions', ['source_transaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('balance_points_credit_card_id_fkey'), 'balance_points', 'credit_cards', ['credit_card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uix_balance_points_account_date', 'balance_points', type_='unique')
    op.drop_index('ix_balance_points_status', table_name='balance_points')
    op.drop_index('ix_balance_points_account_status', table_name='balance_points')
    op.drop_index('ix_balance_points_account_date', table_name='balance_points')
    op.create_index(op.f('ix_balance_points_verified'), 'balance_points', ['is_verified'], unique=False)
    op.create_index(op.f('ix_balance_points_user_date'), 'balance_points', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_balance_points_source_transaction'), 'balance_points', ['source_transaction_id'], unique=False)
    op.create_index(op.f('ix_balance_points_snapshot_type'), 'balance_points', ['snapshot_type'], unique=False)
    op.create_index(op.f('ix_balance_points_date'), 'balance_points', ['date'], unique=False)
    op.create_index(op.f('ix_balance_points_credit_card_id'), 'balance_points', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_balance_points_calculated_at'), 'balance_points', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_balance_points_account_id'), 'balance_points', ['account_id'], unique=False)
    op.create_index(op.f('ix_balance_points_account_calculated_at'), 'balance_points', ['account_id', 'calculated_at'], unique=False)
    op.alter_column('balance_points', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('balance_points', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('balance_points', 'has_transactions')
    op.drop_column('balance_points', 'timeline_status')
    # ### end Alembic commands ###
