name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install fastapi uvicorn sqlalchemy psycopg2-binary pydantic
        pip install awscli
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x "*.git*"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to Elastic Beanstalk
      run: |
        echo "Deploying application..."
        aws s3 cp deploy.zip s3://${{ secrets.AWS_S3_BUCKET_FOR_DEPLOYS }}/deploy.zip
        aws elasticbeanstalk create-application-version \
          --application-name better-call-buffet \
          --source-bundle S3Bucket=${{ secrets.AWS_S3_BUCKET_FOR_DEPLOYS }},S3Key=deploy.zip \
          --process
        aws elasticbeanstalk update-environment \
          --application-name better-call-buffet \
          --environment-name Better-call-buffet-prod-env \
          --version-label latest

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Deployment Status
        run: |
          if [ ${{ needs.deploy.result }} == 'success' ]; then
            echo "✅ Deployment completed successfully"
          else
            echo "❌ Deployment failed"
          fi 