name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the CI workflow succeeded or if manually triggered
    # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        elif [ -f pyproject.toml ]; then
          pip install poetry==1.6.1
          poetry export -f requirements.txt --output requirements.txt --without-hashes || echo "Poetry export failed, continuing..."
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install fastapi uvicorn sqlalchemy psycopg2-binary pydantic
          fi
        else
          pip install fastapi uvicorn sqlalchemy psycopg2-binary pydantic
        fi
        # Install the Elastic Beanstalk CLI
        pip install awsebcli
    
    - name: Generate deployment package
      run: |
        # Create Procfile
        echo "web: python -m uvicorn app.main:app --host 0.0.0.0 --port \$PORT" > Procfile
        
        # Create necessary directories
        mkdir -p .ebextensions logs
        
        # Create Python config
        cat > .ebextensions/01_python.config << EOF
        option_settings:
          aws:elasticbeanstalk:container:python:
            WSGIPath: app.main:app
          aws:elasticbeanstalk:application:environment:
            PYTHONPATH: "/var/app/current"
        EOF
        
        # Create logging config
        cat > .ebextensions/02_logging.config << EOF
        files:
          "/opt/elasticbeanstalk/tasks/publishlogs.d/better-call-buffet.conf":
            mode: "000755"
            owner: root
            group: root
            content: |
              /var/app/current/logs/*.log
              /var/app/current/logs/*.err
              
          "/etc/logrotate.elasticbeanstalk.hourly/logrotate.elasticbeanstalk.better-call-buffet.conf":
            mode: "000755"
            owner: root
            group: root
            content: |
              /var/app/current/logs/*.log {
                size 10M
                rotate 5
                missingok
                compress
                notifempty
                copytruncate
                dateext
                dateformat -%Y%m%d-%H%M%S
              }
        EOF
        
        touch logs/app.log
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to Elastic Beanstalk
      run: |
        # Initialize the EB CLI
        eb init better-call-buffet --region us-east-1 --platform python
        
        # Deploy to the environment
        eb deploy Better-call-buffet-prod-env --label app-${{ github.sha }}
        
    - name: Verify deployment
      run: |
        echo "Deployment to Elastic Beanstalk completed!"
        echo "Application URL: http://Better-call-buffet-prod-env.elasticbeanstalk.com"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Deployment Status
        run: |
          if [ ${{ needs.deploy.result }} == 'success' ]; then
            echo "✅ Deployment completed successfully"
          else
            echo "❌ Deployment failed"
          fi 